/* tslint:disable */
/* eslint-disable */
/**
 * swapi.dev
 * Adapted schema for swapi.dev
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { Planet } from "../models";
/**
 * PlanetsApi - axios parameter creator
 * @export
 */
export const PlanetsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Get a specific planet by id.
     * @param {string} id Id of the planet.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPlanetById: async (
      id: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("getPlanetById", "id", id);
      const localVarPath = `/api/planets/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication apikeyQuery required
      await setApiKeyToObject(localVarQueryParameter, "code", configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PlanetsApi - functional programming interface
 * @export
 */
export const PlanetsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PlanetsApiAxiosParamCreator(configuration);
  return {
    /**
     * Get a specific planet by id.
     * @param {string} id Id of the planet.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPlanetById(
      id: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Planet>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPlanetById(
        id,
        options,
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * PlanetsApi - factory interface
 * @export
 */
export const PlanetsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PlanetsApiFp(configuration);
  return {
    /**
     * Get a specific planet by id.
     * @param {PlanetsApiGetPlanetByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPlanetById(
      requestParameters: PlanetsApiGetPlanetByIdRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<Planet> {
      return localVarFp
        .getPlanetById(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for getPlanetById operation in PlanetsApi.
 * @export
 * @interface PlanetsApiGetPlanetByIdRequest
 */
export interface PlanetsApiGetPlanetByIdRequest {
  /**
   * Id of the planet.
   * @type {string}
   * @memberof PlanetsApiGetPlanetById
   */
  readonly id: string;
}

/**
 * PlanetsApi - object-oriented interface
 * @export
 * @class PlanetsApi
 * @extends {BaseAPI}
 */
export class PlanetsApi extends BaseAPI {
  /**
   * Get a specific planet by id.
   * @param {PlanetsApiGetPlanetByIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PlanetsApi
   */
  public getPlanetById(
    requestParameters: PlanetsApiGetPlanetByIdRequest,
    options?: AxiosRequestConfig,
  ) {
    return PlanetsApiFp(this.configuration)
      .getPlanetById(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
