/* tslint:disable */
/* eslint-disable */
/**
 * swapi.dev
 * Adapted schema for swapi.dev
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Film
 */
export interface Film {
  /**
   * The title of this film.
   * @type {string}
   * @memberof Film
   */
  title: string;
  /**
   * The episode number of this film.
   * @type {number}
   * @memberof Film
   */
  episode_id: number;
  /**
   * The opening paragraphs at the beginning of this film.
   * @type {string}
   * @memberof Film
   */
  opening_crawl: string;
  /**
   * The name of the director of this film.
   * @type {string}
   * @memberof Film
   */
  director: string;
  /**
   * The name(s) of the producer(s) of this film. Comma separated.
   * @type {string}
   * @memberof Film
   */
  producer: string;
  /**
   * An array of species resource URLs that are in this film.
   * @type {Array<string>}
   * @memberof Film
   */
  species: Array<string>;
  /**
   * An array of starship resource URLs that are in this film.
   * @type {Array<string>}
   * @memberof Film
   */
  starships: Array<string>;
  /**
   * An array of vehicle resource URLs that are in this film.
   * @type {Array<string>}
   * @memberof Film
   */
  vehicles: Array<string>;
  /**
   * An array of people resource URLs that are in this film.
   * @type {Array<string>}
   * @memberof Film
   */
  characters: Array<string>;
  /**
   * An array of planet resource URLs that are in this film.
   * @type {Array<string>}
   * @memberof Film
   */
  planets: Array<string>;
  /**
   * The hypermedia URL of this resource.
   * @type {string}
   * @memberof Film
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   * @type {string}
   * @memberof Film
   */
  created: string;
  /**
   * The ISO 8601 date format of the time that this resource was edited.
   * @type {string}
   * @memberof Film
   */
  edited: string;
}
