/* tslint:disable */
/* eslint-disable */
/**
 * swapi.dev
 * Adapted schema for swapi.dev
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Person
 */
export interface Person {
  /**
   * The name of this person.
   * @type {string}
   * @memberof Person
   */
  name: string;
  /**
   * The birth year of the person, using the in-universe standard of BBY or ABY - Before the Battle of Yavin or After the Battle of Yavin. The Battle of Yavin is a battle that occurs at the end of Star Wars episode IV: A New Hope.
   * @type {string}
   * @memberof Person
   */
  birth_year: string;
  /**
   * The eye color of this person. Will be \"unknown\" if not known or \"n/a\" if the person does not have an eye.
   * @type {string}
   * @memberof Person
   */
  eye_color: string;
  /**
   * The gender of this person. Either \"Male\", \"Female\" or \"unknown\", \"n/a\" if the person does not have a gender.
   * @type {string}
   * @memberof Person
   */
  gender: string;
  /**
   * The hair color of this person. Will be \"unknown\" if not known or \"n/a\" if the person does not have hair.
   * @type {string}
   * @memberof Person
   */
  hair_color: string;
  /**
   * The height of the person in centimeters.
   * @type {string}
   * @memberof Person
   */
  height: string;
  /**
   * The mass of the person in kilograms.
   * @type {string}
   * @memberof Person
   */
  mass: string;
  /**
   * The skin color of this person.
   * @type {string}
   * @memberof Person
   */
  skin_color: string;
  /**
   * The URL of a planet resource, a planet that this person was born on or inhabits.
   * @type {string}
   * @memberof Person
   */
  homeworld: string;
  /**
   * An array of film resource URLs that this person has been in.
   * @type {Array<string>}
   * @memberof Person
   */
  films: Array<string>;
  /**
   * An array of species resource URLs that this person belongs to.
   * @type {Array<string>}
   * @memberof Person
   */
  species: Array<string>;
  /**
   * An array of starship resource URLs that this person has piloted.
   * @type {Array<string>}
   * @memberof Person
   */
  starships: Array<string>;
  /**
   * An array of vehicle resource URLs that this person has piloted.
   * @type {Array<string>}
   * @memberof Person
   */
  vehicles: Array<string>;
  /**
   * The hypermedia URL of this resource.
   * @type {string}
   * @memberof Person
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   * @type {string}
   * @memberof Person
   */
  created: string;
  /**
   * The ISO 8601 date format of the time that this resource was edited.
   * @type {string}
   * @memberof Person
   */
  edited: string;
}
