/* tslint:disable */
/* eslint-disable */
/**
 * swapi.dev
 * Adapted schema for swapi.dev
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Planet
 */
export interface Planet {
  /**
   * The name of this planet.
   * @type {string}
   * @memberof Planet
   */
  name: string;
  /**
   * The diameter of this planet in kilometers.
   * @type {string}
   * @memberof Planet
   */
  diameter: string;
  /**
   * The number of standard hours it takes for this planet to complete a single rotation on its axis.
   * @type {string}
   * @memberof Planet
   */
  rotation_period: string;
  /**
   * The number of standard days it takes for this planet to complete a single orbit of its local star.
   * @type {string}
   * @memberof Planet
   */
  orbital_period: string;
  /**
   * A number denoting the gravity of this planet, where \"1\" is normal or 1 standard G. \"2\" is twice or 2 standard Gs. \"0.5\" is half or 0.5 standard Gs.
   * @type {string}
   * @memberof Planet
   */
  gravity: string;
  /**
   * The average population of sentient beings inhabiting this planet.
   * @type {string}
   * @memberof Planet
   */
  population: string;
  /**
   * The climate of this planet. Comma separated if diverse.
   * @type {string}
   * @memberof Planet
   */
  climate: string;
  /**
   * The terrain of this planet. Comma separated if diverse.
   * @type {string}
   * @memberof Planet
   */
  terrain: string;
  /**
   * The percentage of the planet surface that is naturally occurring water or bodies of water.
   * @type {string}
   * @memberof Planet
   */
  surface_water: string;
  /**
   * An array of Film URL Resources that this planet has appeared in.
   * @type {Array<string>}
   * @memberof Planet
   */
  films: Array<string>;
  /**
   * An array of People URL Resources that live on this planet.
   * @type {Array<string>}
   * @memberof Planet
   */
  residents: Array<string>;
  /**
   * The hypermedia URL of this resource.
   * @type {string}
   * @memberof Planet
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   * @type {string}
   * @memberof Planet
   */
  created: string;
  /**
   * The ISO 8601 date format of the time that this resource was edited.
   * @type {string}
   * @memberof Planet
   */
  edited: string;
}
