/* tslint:disable */
/* eslint-disable */
/**
 * swapi.dev
 * Adapted schema for swapi.dev
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Film } from "./film";
// May contain unused imports in some cases
// @ts-ignore
import { Person } from "./person";

/**
 *
 * @export
 * @interface Species
 */
export interface Species {
  /**
   * The name of this species.
   * @type {string}
   * @memberof Species
   */
  name: string;
  /**
   * The classification of this species, such as \"mammal\" or \"reptile\".
   * @type {string}
   * @memberof Species
   */
  classification: string;
  /**
   * The designation of this species, such as \"sentient\".
   * @type {string}
   * @memberof Species
   */
  designation: string;
  /**
   * The average height of this species in centimeters.
   * @type {string}
   * @memberof Species
   */
  average_height: string;
  /**
   * The average lifespan of this species in years.
   * @type {string}
   * @memberof Species
   */
  average_lifespan: string;
  /**
   * A comma-separated string of common eye colors for this species, \"none\" if this species does not typically have eyes.
   * @type {string}
   * @memberof Species
   */
  eye_colors: string;
  /**
   * A comma-separated string of common hair colors for this species, \"none\" if this species does not typically have hair.
   * @type {string}
   * @memberof Species
   */
  hair_colors: string;
  /**
   * A comma-separated string of common skin colors for this species, \"none\" if this species does not typically have skin.
   * @type {string}
   * @memberof Species
   */
  skin_colors: string;
  /**
   * The language commonly spoken by this species.
   * @type {string}
   * @memberof Species
   */
  language: string;
  /**
   * The URL of a planet resource, a planet that this species originates from.
   * @type {string}
   * @memberof Species
   */
  homeworld: string;
  /**
   * An array of People URL Resources that are a part of this species.
   * @type {Array<Person>}
   * @memberof Species
   */
  people: Array<Person>;
  /**
   * An array of Film URL Resources that this species has appeared in.
   * @type {Array<Film>}
   * @memberof Species
   */
  films: Array<Film>;
  /**
   * The hypermedia URL of this resource.
   * @type {string}
   * @memberof Species
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   * @type {string}
   * @memberof Species
   */
  created: string;
  /**
   * The ISO 8601 date format of the time that this resource was edited.
   * @type {string}
   * @memberof Species
   */
  edited: string;
}
