/* tslint:disable */
/* eslint-disable */
/**
 * swapi.dev
 * Adapted schema for swapi.dev
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Starship
 */
export interface Starship {
  /**
   * The name of this starship. The common name, such as \"Death Star\".
   * @type {string}
   * @memberof Starship
   */
  name: string;
  /**
   * The model or official name of this starship. Such as \"T-65 X-wing\" or \"DS-1 Orbital Battle Station\".
   * @type {string}
   * @memberof Starship
   */
  model: string;
  /**
   * The class of this starship, such as \"Starfighter\" or \"Deep Space Mobile Battlestation\".
   * @type {string}
   * @memberof Starship
   */
  starship_class: string;
  /**
   * The manufacturer of this starship. Comma separated if more than one.
   * @type {string}
   * @memberof Starship
   */
  manufacturer: string;
  /**
   * The cost of this starship new, in galactic credits.
   * @type {string}
   * @memberof Starship
   */
  cost_in_credits: string;
  /**
   * The length of this starship in meters.
   * @type {string}
   * @memberof Starship
   */
  length: string;
  /**
   * The number of personnel needed to run or pilot this starship.
   * @type {string}
   * @memberof Starship
   */
  crew: string;
  /**
   * The number of non-essential people this starship can transport.
   * @type {string}
   * @memberof Starship
   */
  passengers: string;
  /**
   * The maximum speed of this starship in the atmosphere. \"N/A\" if this starship is incapable of atmospheric flight.
   * @type {string}
   * @memberof Starship
   */
  max_atmosphering_speed: string;
  /**
   * The class of this starship\'s hyperdrive.
   * @type {string}
   * @memberof Starship
   */
  hyperdrive_rating: string;
  /**
   * The Maximum number of Megalights this starship can travel in a standard hour. A \"Megalight\" is a standard unit of distance and has never been defined before within the Star Wars universe. This figure is only really useful for measuring the difference in speed of starships. We can assume it is similar to AU, the distance between our Sun (Sol) and Earth.
   * @type {string}
   * @memberof Starship
   */
  MGLT: string;
  /**
   * The maximum number of kilograms that this starship can transport.
   * @type {string}
   * @memberof Starship
   */
  cargo_capacity: string;
  /**
   * The maximum length of time that this starship can provide consumables for its entire crew without having to resupply.
   * @type {string}
   * @memberof Starship
   */
  consumables: string;
  /**
   * An array of Film URL Resources that this starship has appeared in.
   * @type {Array<string>}
   * @memberof Starship
   */
  films: Array<string>;
  /**
   * An array of People URL Resources that this starship has been piloted by.
   * @type {Array<string>}
   * @memberof Starship
   */
  pilots: Array<string>;
  /**
   * The hypermedia URL of this resource.
   * @type {string}
   * @memberof Starship
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   * @type {string}
   * @memberof Starship
   */
  created: string;
  /**
   * The ISO 8601 date format of the time that this resource was edited.
   * @type {string}
   * @memberof Starship
   */
  edited: string;
}
