/* tslint:disable */
/* eslint-disable */
/**
 * swapi.dev
 * Adapted schema for swapi.dev
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Vehicle
 */
export interface Vehicle {
  /**
   * The name of this vehicle. The common name, such as \"Sand Crawler\" or \"Speeder bike\".
   * @type {string}
   * @memberof Vehicle
   */
  name: string;
  /**
   * The model or official name of this vehicle. Such as \"All-Terrain Attack Transport\".
   * @type {string}
   * @memberof Vehicle
   */
  model: string;
  /**
   * The class of this vehicle, such as \"Wheeled\" or \"Repulsorcraft\".
   * @type {string}
   * @memberof Vehicle
   */
  vehicle_class: string;
  /**
   * The manufacturer of this vehicle. Comma separated if more than one.
   * @type {string}
   * @memberof Vehicle
   */
  manufacturer: string;
  /**
   * The length of this vehicle in meters.
   * @type {string}
   * @memberof Vehicle
   */
  length: string;
  /**
   * The cost of this vehicle new, in Galactic Credits.
   * @type {string}
   * @memberof Vehicle
   */
  cost_in_credits: string;
  /**
   * The number of personnel needed to run or pilot this vehicle.
   * @type {string}
   * @memberof Vehicle
   */
  crew: string;
  /**
   * The number of non-essential people this vehicle can transport.
   * @type {string}
   * @memberof Vehicle
   */
  passengers: string;
  /**
   * The maximum speed of this vehicle in the atmosphere.
   * @type {string}
   * @memberof Vehicle
   */
  max_atmosphering_speed: string;
  /**
   * The maximum number of kilograms that this vehicle can transport.
   * @type {string}
   * @memberof Vehicle
   */
  cargo_capacity: string;
  /**
   * The maximum length of time that this vehicle can provide consumables for its entire crew without having to resupply.
   * @type {string}
   * @memberof Vehicle
   */
  consumables: string;
  /**
   * An array of Film URL Resources that this vehicle has appeared in.
   * @type {Array<string>}
   * @memberof Vehicle
   */
  films: Array<string>;
  /**
   * An array of People URL Resources that this vehicle has been piloted by.
   * @type {Array<string>}
   * @memberof Vehicle
   */
  pilots: Array<string>;
  /**
   * The hypermedia URL of this resource.
   * @type {string}
   * @memberof Vehicle
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   * @type {string}
   * @memberof Vehicle
   */
  created: string;
  /**
   * The ISO 8601 date format of the time that this resource was edited.
   * @type {string}
   * @memberof Vehicle
   */
  edited: string;
}
